### PR TITLE
Make content type optional

### PR DESCRIPTION
**Pull request by RabidCicada**
This is to address #57.  We could also, instead of defaulting to None, set the default to 'application/octect-stream'.  Please provide feedback etc.

### CODE REVIEW

**Comment by RabidCicada** [comment]
The failures are in the testing pipeline I believe and not related to the changes made.  They failed locally with 3.4 also.

**Comment by ornoone** [comment]
hey @RabidCicada, thanks for the work and sorry for the delay.

your PR seem pretty simple and good, can you just provide a unit test to reproduce your initial error if you had one ?
the way it should be is : add your test without your fix => it should fail. add your fix after and it should be all clear.
I will investigate about failing testing pipeline today.

**Comment by RabidCicada** [comment]
I will fix.  Probably next two days.  With your approval I will also add a DEFAULT_CONTENT_TYPE setting so that people can configure it themselves and Django Rest Models will assume a content type if not given one on the file object.  Does that sound reasonable?

**Comment by ornoone** [comment]
sound reasonable to me :)

**Pull request closed without merging**
